export async function exportPDF(docs, videoName, meta = {}) {
  const { default: jsPDF } = await import("jspdf")
  const title = (meta.title && meta.title.trim()) || "Step-by-Step Guide"
  const tools = meta.tools || []
  const pdf = new jsPDF({ unit: "mm", format: "a4" })

  const pageW = 210
  const pageH = 297
  const margin = 18
  const contentW = pageW - margin * 2
  let y = margin

  const newPageIfNeeded = (needed) => {
    if (y + needed > pageH - margin) {
      pdf.addPage()
      y = margin
    }
  }

  // Title
  pdf.setFontSize(20)
  pdf.setFont("helvetica", "bold")
  pdf.setTextColor(228, 228, 231)
  pdf.text(title, margin, y)
  y += 8

  pdf.setFontSize(9)
  pdf.setFont("helvetica", "normal")
  pdf.setTextColor(113, 113, 122)
  pdf.text(`Generated by VideoDoc  •  ${new Date().toLocaleDateString()}`, margin, y)
  y += 6
  if (tools.length) {
    pdf.setTextColor(16, 122, 106)
    pdf.text(`Tools used: ${tools.join(", ")}`, margin, y)
    y += 6
  }
  y += 6

  // Divider
  pdf.setDrawColor(39, 39, 42)
  pdf.line(margin, y, pageW - margin, y)
  y += 8

  for (const doc of docs) {
    // Estimate height needed
    const transcriptLines = pdf.splitTextToSize(doc.text, contentW - (doc.frame ? 42 : 0))
    const annoLines = doc.annotation ? pdf.splitTextToSize(doc.annotation, contentW - (doc.frame ? 42 : 0)) : []
    const blockH = Math.max(28, transcriptLines.length * 4.8 + annoLines.length * 4.2 + 12)
    newPageIfNeeded(blockH)

    // Timestamp badge
    pdf.setFontSize(8)
    pdf.setFont("courier", "bold")
    pdf.setTextColor(52, 211, 153)
    pdf.text(`[${doc.label}]`, margin, y)
    y += 5

    const textX = doc.frame ? margin + 38 : margin
    const textW = doc.frame ? contentW - 38 : contentW

    // Thumbnail
    if (doc.frame) {
      try {
        pdf.addImage(doc.frame, "JPEG", margin, y, 34, 20)
      } catch {
        // skip image if it fails
      }
    }

    // Transcript
    pdf.setFontSize(9)
    pdf.setFont("helvetica", "normal")
    pdf.setTextColor(212, 212, 216)
    const tLines = pdf.splitTextToSize(doc.text, textW)
    pdf.text(tLines, textX, y)
    y += tLines.length * 4.8

    // Annotation
    if (doc.annotation) {
      pdf.setFontSize(8)
      pdf.setTextColor(113, 113, 122)
      const aLines = pdf.splitTextToSize(doc.annotation, textW)
      pdf.text(aLines, textX, y + 2)
      y += aLines.length * 4.2 + 2
    }

    y += 10

    // Divider
    pdf.setDrawColor(39, 39, 42)
    pdf.line(margin, y - 3, pageW - margin, y - 3)
  }

  pdf.save(`${title}-docs.pdf`)
}
