export async function exportPDF(docs, videoName, meta = {}) {
  const { default: jsPDF } = await import("jspdf")
  const title = (meta.title && meta.title.trim()) || "Step-by-Step Guide"
  const company = (meta.company && meta.company.trim()) || ""
  const insights = meta.insights || {}
  const faqs = Array.isArray(insights.faqs) ? insights.faqs : []
  const flowImage = meta.flowImage || null
  const tools = meta.tools || []
  const pdf = new jsPDF({ unit: "mm", format: "a4" })

  const pageW = 210, pageH = 297, margin = 18
  const contentW = pageW - margin * 2
  let y = margin

  const ensure = (needed) => { if (y + needed > pageH - margin) { pdf.addPage(); y = margin } }
  const heading = (text) => {
    ensure(14); y += 3
    pdf.setFontSize(13); pdf.setFont("helvetica", "bold"); pdf.setTextColor(26, 24, 20)
    pdf.text(text, margin, y); y += 6.5
  }
  const body = (text, { size = 10, color = [40, 40, 40], indent = 0, bold = false } = {}) => {
    pdf.setFontSize(size); pdf.setFont("helvetica", bold ? "bold" : "normal"); pdf.setTextColor(...color)
    const lines = pdf.splitTextToSize(text, contentW - indent)
    for (const ln of lines) { ensure(size * 0.55); pdf.text(ln, margin + indent, y); y += size * 0.5 }
  }
  const divider = () => { ensure(4); pdf.setDrawColor(210, 205, 196); pdf.line(margin, y, pageW - margin, y); y += 5 }

  // Company name — top-right of the first page
  if (company) {
    pdf.setFontSize(11); pdf.setFont("helvetica", "bold"); pdf.setTextColor(16, 122, 106)
    pdf.text(company, pageW - margin, y, { align: "right" })
  }

  // Title
  pdf.setFontSize(20); pdf.setFont("helvetica", "bold"); pdf.setTextColor(20, 18, 14)
  pdf.text(title, margin, y); y += 8
  pdf.setFontSize(9); pdf.setFont("helvetica", "normal"); pdf.setTextColor(120, 120, 120)
  pdf.text(`Generated by VideoDoc  •  ${new Date().toLocaleDateString()}`, margin, y); y += 5
  if (tools.length) {
    pdf.setTextColor(16, 122, 106)
    const tl = pdf.splitTextToSize(`Tools used: ${tools.join(", ")}`, contentW)
    pdf.text(tl, margin, y); y += tl.length * 4.4
  }
  y += 3
  divider()

  const purpose = insights.purpose || ""
  const prerequisites = Array.isArray(insights.prerequisites) ? insights.prerequisites : []
  const keyObs = Array.isArray(insights.keyObservations) ? insights.keyObservations : []

  // Purpose
  if (purpose) {
    heading("Purpose")
    for (const para of purpose.split(/\n\n+/)) if (para.trim()) { body(para.trim(), { size: 10.5, color: [40, 38, 34] }); y += 2 }
    y += 2
  }

  // Prerequisites
  if (prerequisites.length || tools.length) {
    heading("Prerequisites")
    for (const p of prerequisites) body(`•  ${p}`, { size: 10, color: [40, 38, 34], indent: 2 })
    if (tools.length) body(`•  Tools / systems: ${tools.join(", ")}`, { size: 10, color: [40, 38, 34], indent: 2 })
    y += 3
  }

  // Procedure
  heading("Procedure")
  let stepNo = 0
  for (const doc of docs) {
    stepNo++
    ensure(18)
    const stepTitle = doc.step?.title || (doc.text || "").slice(0, 60) || `Step ${stepNo}`
    pdf.setFontSize(11); pdf.setFont("helvetica", "bold"); pdf.setTextColor(16, 122, 106)
    const hLines = pdf.splitTextToSize(`Step ${stepNo}: ${stepTitle}`, contentW - 22)
    pdf.text(hLines, margin, y)
    pdf.setFontSize(8); pdf.setFont("courier", "normal"); pdf.setTextColor(150, 148, 142)
    pdf.text(doc.label || "", pageW - margin, y, { align: "right" })
    y += hLines.length * 5 + 1.5

    const textX = doc.frame ? margin + 38 : margin
    const textW = doc.frame ? contentW - 38 : contentW
    const yStart = y
    if (doc.frame) { try { pdf.addImage(doc.frame, "JPEG", margin, y, 34, 20) } catch { /* skip image */ } }

    const step = doc.step
    if (step) {
      pdf.setFont("helvetica", "normal")
      ;(step.steps || []).forEach((s, i) => {
        pdf.setFontSize(9.5); pdf.setTextColor(40, 38, 34)
        const lines = pdf.splitTextToSize(`${i + 1}. ${s}`, textW)
        for (const ln of lines) { ensure(4.6); pdf.text(ln, textX, y); y += 4.5 }
      })
      if (step.result) {
        pdf.setFontSize(9.5); pdf.setTextColor(16, 122, 106)
        const rl = pdf.splitTextToSize(`Result: ${step.result}`, textW)
        for (const ln of rl) { ensure(4.6); pdf.text(ln, textX, y); y += 4.5 }
      }
      if (step.note) {
        pdf.setFontSize(9); pdf.setFont("helvetica", "italic"); pdf.setTextColor(140, 110, 30)
        const nl = pdf.splitTextToSize(`Note: ${step.note}`, textW)
        for (const ln of nl) { ensure(4.4); pdf.text(ln, textX, y); y += 4.3 }
        pdf.setFont("helvetica", "normal")
      }
    } else if (doc.annotation) {
      pdf.setFontSize(9); pdf.setTextColor(60, 58, 52)
      const aLines = pdf.splitTextToSize(doc.annotation, textW)
      for (const ln of aLines) { ensure(4.4); pdf.text(ln, textX, y); y += 4.3 }
    }

    if (doc.frame && y < yStart + 22) y = yStart + 22 // keep room for the thumbnail
    y += 5
    divider()
  }

  // Key Observations
  if (keyObs.length) {
    heading("Key Observations & Notes")
    for (const o of keyObs) body(`•  ${o}`, { size: 10, color: [40, 38, 34], indent: 2 })
    y += 3
  }

  // Summary
  if (insights.summary) {
    heading("Summary")
    for (const para of insights.summary.split(/\n\n+/)) if (para.trim()) { body(para.trim(), { size: 10.5, color: [40, 38, 34] }); y += 2 }
    y += 2
  }

  // FAQ
  if (faqs.length) {
    heading("FAQ")
    for (const f of faqs) {
      body(`Q: ${f.q}`, { size: 10.5, color: [26, 24, 20], bold: true }); y += 1
      body(`A: ${f.a}`, { size: 10, color: [60, 58, 52] }); y += 3
    }
  }

  // Process Flow (at the end)
  if (flowImage?.dataUrl) {
    heading("Process Flow")
    try {
      const aspect = (flowImage.height || 300) / (flowImage.width || 600)
      let imgW = contentW, imgH = imgW * aspect
      const maxH = pageH - margin * 2 - 10
      if (imgH > maxH) { imgH = maxH; imgW = imgH / aspect }
      ensure(imgH + 4)
      pdf.addImage(flowImage.dataUrl, "PNG", margin + (contentW - imgW) / 2, y, imgW, imgH)
      y += imgH + 6
    } catch { /* skip diagram on failure */ }
  }

  pdf.save(`${title}-docs.pdf`)
}
