function dataUrlToUint8(dataUrl) {
  const base64 = dataUrl.split(",")[1]
  const bin = atob(base64)
  const bytes = new Uint8Array(bin.length)
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i)
  return bytes
}

export async function exportDOCX(docs, videoName, meta = {}) {
  const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle, ImageRun } = await import("docx")
  const title = (meta.title && meta.title.trim()) || "Step-by-Step Guide"
  const company = (meta.company && meta.company.trim()) || ""
  const insights = meta.insights || {}
  const faqs = Array.isArray(insights.faqs) ? insights.faqs : []
  const flowImage = meta.flowImage || null
  const tools = meta.tools || []

  const children = []

  // Company name — top-right
  if (company) {
    children.push(new Paragraph({
      alignment: AlignmentType.RIGHT,
      children: [new TextRun({ text: company, bold: true, color: "107a6a", size: 22 })],
      spacing: { after: 80 },
    }))
  }

  children.push(new Paragraph({ text: title, heading: HeadingLevel.HEADING_1 }))
  children.push(new Paragraph({
    children: [new TextRun({ text: `Generated by VideoDoc  •  ${new Date().toLocaleDateString()}`, color: "71717a", size: 18 })],
    spacing: { after: tools.length ? 120 : 300 },
  }))

  if (tools.length) {
    children.push(new Paragraph({
      children: [
        new TextRun({ text: "Tools used: ", bold: true, color: "107a6a", size: 18 }),
        new TextRun({ text: tools.join(", "), color: "107a6a", size: 18 }),
      ],
      spacing: { after: 300 },
    }))
  }

  const purpose = insights.purpose || ""
  const prerequisites = Array.isArray(insights.prerequisites) ? insights.prerequisites : []
  const keyObs = Array.isArray(insights.keyObservations) ? insights.keyObservations : []
  const H2 = (text) => new Paragraph({ text, heading: HeadingLevel.HEADING_2, spacing: { before: 240, after: 100 } })

  // Purpose
  if (purpose) {
    children.push(H2("Purpose"))
    for (const para of purpose.split(/\n\n+/)) {
      const t = para.trim()
      if (t) children.push(new Paragraph({ children: [new TextRun({ text: t, size: 22 })], spacing: { after: 120 } }))
    }
  }

  // Prerequisites
  if (prerequisites.length || tools.length) {
    children.push(H2("Prerequisites"))
    for (const p of prerequisites) children.push(new Paragraph({ text: p, bullet: { level: 0 }, spacing: { after: 40 } }))
    if (tools.length) children.push(new Paragraph({
      children: [new TextRun({ text: "Tools / systems: ", bold: true }), new TextRun({ text: tools.join(", ") })],
      bullet: { level: 0 },
    }))
  }

  // Procedure
  children.push(H2("Procedure"))
  let stepNo = 0
  for (const doc of docs) {
    stepNo++
    const stepTitle = doc.step?.title || (doc.text || "").slice(0, 70) || `Step ${stepNo}`
    children.push(new Paragraph({
      heading: HeadingLevel.HEADING_3,
      spacing: { before: 220, after: 60 },
      children: [
        new TextRun({ text: `Step ${stepNo}: `, bold: true, color: "107a6a", size: 24 }),
        new TextRun({ text: stepTitle, bold: true, size: 24 }),
        new TextRun({ text: `   [${doc.label}]`, size: 16, color: "9a958c" }),
      ],
    }))

    if (doc.frame) {
      try {
        children.push(new Paragraph({
          children: [new ImageRun({ data: dataUrlToUint8(doc.frame), transformation: { width: 280, height: 158 } })],
          spacing: { after: 100 },
        }))
      } catch { /* skip thumbnail */ }
    }

    const step = doc.step
    if (step) {
      (step.steps || []).forEach((s, i) => children.push(new Paragraph({
        children: [new TextRun({ text: `${i + 1}. `, bold: true }), new TextRun({ text: s, size: 21 })],
        spacing: { after: 30 }, indent: { left: 220 },
      })))
      if (step.result) children.push(new Paragraph({
        children: [new TextRun({ text: "Result: ", bold: true, color: "107a6a", size: 21 }), new TextRun({ text: step.result, color: "107a6a", size: 21 })],
        spacing: { before: 40, after: 40 },
      }))
      if (step.note) children.push(new Paragraph({
        children: [new TextRun({ text: "Note: ", bold: true, italics: true, color: "8a6d1e", size: 20 }), new TextRun({ text: step.note, italics: true, color: "8a6d1e", size: 20 })],
        spacing: { after: 80 },
      }))
    } else if (doc.annotation) {
      children.push(new Paragraph({ children: [new TextRun({ text: doc.annotation, size: 20 })], spacing: { after: 80 } }))
    }
  }

  // Key Observations
  if (keyObs.length) {
    children.push(H2("Key Observations & Notes"))
    for (const o of keyObs) children.push(new Paragraph({ text: o, bullet: { level: 0 }, spacing: { after: 40 } }))
  }

  // Summary
  if (insights.summary) {
    children.push(H2("Summary"))
    for (const para of insights.summary.split(/\n\n+/)) {
      const t = para.trim()
      if (t) children.push(new Paragraph({ children: [new TextRun({ text: t, size: 22 })], spacing: { after: 120 } }))
    }
  }

  // FAQ
  if (faqs.length) {
    children.push(H2("FAQ"))
    for (const f of faqs) {
      children.push(new Paragraph({ children: [new TextRun({ text: `Q: ${f.q}`, bold: true, size: 22 })], spacing: { before: 120, after: 40 } }))
      children.push(new Paragraph({ children: [new TextRun({ text: `A: ${f.a}`, size: 22, color: "3f3f46" })], spacing: { after: 80 } }))
    }
  }

  // Process Flow (rasterised PNG, at the end)
  if (flowImage?.dataUrl) {
    children.push(H2("Process Flow"))
    try {
      const maxW = 600
      const scale = Math.min(1, maxW / (flowImage.width || maxW))
      children.push(new Paragraph({
        alignment: AlignmentType.CENTER,
        children: [new ImageRun({
          data: dataUrlToUint8(flowImage.dataUrl),
          transformation: { width: Math.round((flowImage.width || maxW) * scale), height: Math.round((flowImage.height || 300) * scale) },
        })],
        spacing: { after: 200 },
      }))
    } catch { /* skip diagram if embedding fails */ }
  }

  const document = new Document({
    sections: [{
      properties: {},
      children,
    }],
  })

  const blob = await Packer.toBlob(document)
  const url = URL.createObjectURL(blob)
  const anchor = window.document.createElement("a")
  anchor.href = url
  anchor.download = `${title}-docs.docx`
  anchor.click()
  setTimeout(() => URL.revokeObjectURL(url), 10000)
}
