export async function exportDOCX(docs, videoName) {
  const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle } = await import("docx")
  const title = videoName.replace(/\.[^.]+$/, "")

  const children = [
    new Paragraph({
      text: title,
      heading: HeadingLevel.HEADING_1,
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: `Generated by VideoDoc  •  ${new Date().toLocaleDateString()}`,
          color: "71717a",
          size: 18,
        }),
      ],
      spacing: { after: 400 },
    }),
  ]

  for (const doc of docs) {
    // Timestamp
    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: `[${doc.label}]`,
            color: "34D399",
            bold: true,
            font: "Courier New",
            size: 20,
          }),
        ],
        spacing: { before: 240 },
        border: {
          top: { style: BorderStyle.SINGLE, size: 1, color: "27272A" },
        },
      })
    )

    // Transcript
    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: doc.text,
            size: 20,
            color: "D4D4D8",
          }),
        ],
        spacing: { after: 80 },
      })
    )

    // Annotation
    if (doc.annotation) {
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: doc.annotation,
              italics: true,
              size: 18,
              color: "71717A",
            }),
          ],
          spacing: { after: 120 },
        })
      )
    }
  }

  const document = new Document({
    sections: [{
      properties: {},
      children,
    }],
  })

  const blob = await Packer.toBlob(document)
  const url = URL.createObjectURL(blob)
  const anchor = window.document.createElement("a")
  anchor.href = url
  anchor.download = `${title}-docs.docx`
  anchor.click()
  setTimeout(() => URL.revokeObjectURL(url), 10000)
}
